### ISSUE TITLE
Initial volume appears to do nothing

### ISSUE THREAD

**Issue by Willyarma** [devgianlu/go-librespot#94]
I was just experimenting with audio_device, mixer_device and mixer_control_name.
I had a hard time trying to figure out what names to put for these, but I figured it out in the end.

cheap USB audio device:

audio_device: plughw:3,0
mixer_device: default:3
mixer_control_name: Headphone

rpi4 built in output:

audio_device: plughw:0,0
mixer_device: default:0
mixer_control_name: PCM

However it appears that putting initial_volume: 100 (which is default anyway) in the config.yml doesn't change the volume at all.
I assumed its supposed to set max volume at startup, have I misunderstood this?

If I query the volume with a GET request to /player/volume, its coming back with whatever it was set to before, not 100, (so go-librespot doesn't think its a 100 when its not, i mean)

I was setting the volume to low with alsamixer and then starting up go-librespot to see if it went up again.

It not a huge problem for me because if I send a POST request to /player/volume with {"volume":100} in the body (stringified JSON) this works and I can just do this from my own program.

**Comment by Willyarma** [comment]
I noticed after that others have open similar tickets.
I'm still learning how go-librespot works at the moment, forgive me if I have created a duplicate or has asked something that isnt planned or I have misunderstood.

**Comment by devgianlu** [comment]
@Willyarma What you are describing in the last post is correct. I don't see any bug in the `initial_volume` not affecting the ALSA mixer because it would be a bit strange if, for example, the daemon restarts and updates the volume for no reason. I'll make sure to add a note about this.

Regarding the API, I think go-librespot should not provide an endpoint for controlling the underlying audio backend directly as that can be done via other means.
